runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /CSS
  static_dir: CSS
- url: /Javascript
  static_dir: Javascript
- url: /img
  static_dir: img
- url: /(.*\.png)
  mime_type: img/png
  static_files: SBeat/templates/img/\1
  upload: SBeat/templates/img/(.*\.png)
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
